In [3]:
import numpy as np

## Creating array
np.array([1, 2, 4, 5, 3])

array([1, 2, 4, 5, 3])

In [2]:
## Creating a 5-length array filled with zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
## Creating a 4x6 array with ones
np.ones((4, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [5]:
## Creating a 4x6 array filled with 11.31
np.full((4, 6), 11.31)

array([[11.31, 11.31, 11.31, 11.31, 11.31, 11.31],
       [11.31, 11.31, 11.31, 11.31, 11.31, 11.31],
       [11.31, 11.31, 11.31, 11.31, 11.31, 11.31],
       [11.31, 11.31, 11.31, 11.31, 11.31, 11.31]])