# Creating Arrays with Numpy

In [3]:
import numpy as np

## Creating an array
np.array([1, 2, 4, 5, 3])

array([1, 2, 4, 5, 3])

In [2]:
## Creating a 5-length array filled with zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
## Creating a 4x6 array with ones
np.ones((4, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [5]:
## Creating a 4x6 array filled with 11.31
np.full((4, 6), 11.31)

array([[11.31, 11.31, 11.31, 11.31, 11.31, 11.31],
       [11.31, 11.31, 11.31, 11.31, 11.31, 11.31],
       [11.31, 11.31, 11.31, 11.31, 11.31, 11.31],
       [11.31, 11.31, 11.31, 11.31, 11.31, 11.31]])

In [6]:
## Creating an array with five values evenly space between 1 and 7
np.linspace(1, 7, 5)

array([1. , 2.5, 4. , 5.5, 7. ])

In [7]:
## Creating a 2x3 array filled with random values from the uniform(0, 1)
np.random.random((2, 3))

array([[0.88548995, 0.50176363, 0.0796704 ],
       [0.32906098, 0.16188604, 0.0716613 ]])

In [9]:
## Creating a 2x3 array filled with random values from the N(0, 1)
np.random.normal(0, 1, (2, 3))

array([[-1.79020703,  0.86474794,  1.47379429],
       [ 0.84475463, -0.09007823, -0.27791813]])

In [10]:
## Creating a 2x3 array filled with random integers from [1, 20)
np.random.randint(1, 20, (2, 3))

array([[17, 14, 12],
       [ 7,  8, 16]])

In [11]:
## Creating a 4x4 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Numpy Array Attributes

In [12]:
x = np.random.randint(1, 20, (5, 3))
x.ndim

2

In [13]:
x.shape

(5, 3)

In [14]:
x.size

15

# Array Indexing: Accessing Single Elements

In [15]:
x = np.array([1, 2, 4, 5, 3])

## accessing the first array element
x[0]

1

In [16]:
## accessing the third element
x[2]

4

In [17]:
## accessing the last element 
x[-1]

3

In [22]:
y = np.random.randint(1, 20, (2, 3))
y

array([[10,  3, 18],
       [ 9, 17, 10]])

In [23]:
## accessing the (1, 1) element
y[0, 0]

10

In [25]:
## accessing the (2, 3) element
y[1, 2]

10

# Array Slicing: Accessing Subarrays

In [26]:
x = np.array([1, 2, 4, 5, 3])

## accessing the first three elements
x[:3]

array([1, 2, 4])

In [27]:
## accessing after third index
x[3:]

array([5, 3])

In [28]:
## accessing the middle sub-array
x[2:4]

array([4, 5])

In [29]:
## accessing every other element
x[::2]

array([1, 4, 3])

In [30]:
## accessing every other element, starting at index 1
x[1::2]

array([2, 5])

In [31]:
## all elements reversed
x[::-1]

array([3, 5, 4, 2, 1])

In [32]:
## reversed every other elements, starting at index 5
x[5::-2]

array([3, 4, 1])

In [33]:
y = np.random.randint(1, 20, (3, 4))
y

array([[ 1, 10, 14],
       [12,  4, 12]])

In [36]:
## accessing the first column 
y[:, 0]

array([ 1, 12])

In [37]:
## accessing the first row
y[0, :]

array([ 1, 10, 14])

In [35]:
## accessing the first two rows, and the first two columns
y[:2, :2]

array([[ 1, 10],
       [12,  4]])

# Reshaping Arrays 

In [38]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [42]:
## row reshape
x = x.reshape((1, 3))
x

array([[1, 2, 3]])

In [43]:
## columns reshape
x = x.reshape((3, 1))
x

array([[1],
       [2],
       [3]])